language: csharp
mono: none
dotnet: 2.1.3

script:
  - dotnet restore "./Test CLI/Test CLI.sln"
  - dotnet build -r ubuntu.14.04-x64 "./Test CLI/Test CLI.sln"
  - dotnet test -r ubuntu.14.04-x64 "/home/travis/build/veliniv/Test-CLI/Test CLI/CLI.Test"
